
#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "9"
#define VORPALINE_VERSION_PATCH "9"
#define VORPALINE_VERSION "1.9.9-rc"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "2026-03-14 17:39:55"
#define VORPALINE_SVN_REVISION ""

#endif

